baseurl = "https://yuanzheshi.com"
title = "Yuanzhe Shi"

theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20
canonifyurls = true
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Yuanzhe Shi"
    keywords = "blog,developer,personal"
    info = "Developer and Illustrator"
    avatarurl = "images/me.jpg"
    #gravatar = "john.doe@example.com"
    footercontent = "Chem is try"
    dateformat = "January 2, 2006"
    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019
    # Git Commit in Footer, uncomment the line below to enable it.
    rtl = false
    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorsheme = "auto"
    # Series see also post count
    maxSeeAlsoItems = 5
    # Enable Twemoji
    enableTwemoji = true
    # Custom CSS
    custom_css = []
    # Custom JS
    custom_js = []
    # If you want to use fathom(https://usefathom.com) for analytics, add this section

# Cloudflare support
[params.cloudflare]
    token = "token"

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

# Social links
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/whimSYZ/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/yuanzheshi/"
[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 3
    url = "mailto:y327shi@uwaterloo.ca"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url = "posts/"
[[menu.main]]
    name = "Gallery"
    weight = 2
    url  = "gallery/"
#[[menu.main]]
    #name = "Archive"
    #weight = 3
    #url = "archive/"
[[menu.main]]
    name = "Resume"
    weight = 4
    url  = "/yuanzhe_shi_resume_sep_2020_en.pdf"
[[menu.main]]
    name = "About"
    weight = 4
    url = "about/"
